[package]
name = "unsizing-experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
thin-vec = "0.2.12"
trybuild = "1.0.79"
futures = "*"
